##################################
### Main Config For McBoosters ###
##################################
#
#Notes:
#    Do not use ' or " in messages as I have not yet added support for these icons.
#   - Do not remove any lines as that will throw errors
#   - This plugin only supports Minecraft color codes. Ex) &eHello World&7!
#       - Use this link for a list of the codes: https://wiki.ess3.net/mc/
#   - If you want a message to be blank, please leave it as ''
#   - This plugin supports player name place holders as %Player%
# If you receive an error when McBoosters loads, ensure that:
#   - No tabs are present: YAML only allows spaces
#   - Indents are correct: YAML hierarchy is based entirely on indentation
###################################
Configuration:
  #When there are multiple of the same booster active, how should the boost be decided
  StackedBoosterBoost: 'boost + ((extra_boost-1)/2)'
  LangFile: 'en'
  Discord:
    #How many seconds after the last cached message should the plugin wait to listen for others?
    MessageLimiterDuration: 300
    #Only keep pings from the first message, and remove them from all of the other ones
    RemovePings: true