name: McBoosters
version: 1.0-SNAPSHOT
main: com.diamonddagger.mcboosters.McBoosters
api-version: 1.13
softdepend: [McRPG, mcMMO, Jobs]
authors: [DiamondDagger590]
commands:
  mcbooster:
    description: Main Command for McBoosters
    aliases: [mcb, boosters]